version: "3"
services:
  vol_golang:
    container_name: ${GOLANG_CONTAINER_NAME}
    build: ./go
    volumes:
      - ./go/app:/app
    command:
      - "go"
      - "run"
      - "main.go"
    environment:
      WAIT_HOSTS: vol_mysql
      MYSQL_ROOT_HOST: "%"
    ports:
      - "${GOLANG_PORT}:8082"
    env_file:
      - .env
    depends_on:
      vol_mysql:
        condition: service_healthy
  vol_mysql:
    container_name: ${MYSQL_CONTAINER_NAME}
    build: ./mysql
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: gopher
      MYSQL_PASSWORD: setsetset
    cap_add:
      - SYS_NICE
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 20s
      retries: 10
    # ports:
    #   - 33060:3306
networks:
  default:
    external:
      name: vol_network
