version: "3"
services:
  vol_golang:
    container_name: ${golang_container_name}
    build: ./go
    volumes:
      - ./go/app:/app
    command:
      - "go"
      - "run"
      - "main.go"
    environment:
      WAIT_HOSTS: vol_mysql
      MYSQL_ROOT_HOST: "%"
    ports:
      - "${GOLANG_PORT}:8080"
  vol_mysql:
    container_name: ${mysql_container_name}
    build: ./mysql
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: gopher
      MYSQL_PASSWORD: setsetset   
    cap_add:
      - SYS_NICE
    # ports:
    #   - 33060:3306
networks:
  default:
    external:
      name: vol_network
    