version: "3"
services:
  vol_golang:
    container_name: vol_golang
    build: ./go
    volumes:
      - ./go/app:/app
    command:
      - "go"
      - "run"
      - "main.go"
    environment:
      WAIT_HOSTS: vol_mysql
      MYSQL_ROOT_HOST: "%"
    ports:
      - "8082:80"
    networks:
      - vol_network
  vol_mysql:
    container_name: vol_mysql
    build: ./mysql
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: gopher
      MYSQL_PASSWORD: setsetset
    networks:
      - vol_network
    cap_add:
      - SYS_NICE
    # ports:
    #   - 33060:3306
networks:
  vol_network:
    external: true
