# name: deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Deploy
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USERNAME }}
#           port: ${{ secrets.SSH_PORT }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             cd ${{ secrets.SERVER_DEPLOY_DIR }}
#             git pull origin main

name: deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: update
        run: sudo apt update
      - name: install module
        run: sudo apt install wget ssh openssh-server openssh-client
      - name: wget cloudflared
        run: wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm
      - name: rename cloudflare
        run: mv cloudflared-linux-arm cloudflared
      - name: chmod cloudflared
        run: chmod +x cloudflared
      - name: move cloudflared
        run: mv cloudflared /usr/bin
      - name: ssh directory
        run: mkdir -p ~/.ssh
      - name: ssh config
        run: echo "Host ssh-server.kajilab.tk\nHostName ssh-server.kajilab.tk\nUser kjlb\nProxyCommand /usr/bin/cloudflared access ssh --hostname %h\nHost *\nIPQoS cs1" >> ~/.ssh/config
      - name: ssh key
        run: echo "${{ secrets.SSH_KEY }}" >> ~/.ssh/id_rsa
      - name: display ssh key
        run: cat ~/.ssh/id_rsa
      - name: chmod ssh key
        run: chmod 600 ~/.ssh/id_rsa
      - name: ssh
        run: ssh ssh-server.kajilab.tk
      - name: mkdir deploy
        run: mkdir -p ~/deploy
